name: JS Checks

on:
  pull_request:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  js-checks:
    uses: hemilabs/actions/.github/workflows/js-checks.yml@e67f2b7d682accaeb026ebe393f8a161b2daa35b # v2.2.0
