name: NPM Publish

on:
  release:
    types:
      - published

jobs:
  npm-publish:
    permissions:
      contents: read
      id-token: write
    uses: hemilabs/actions/.github/workflows/npm-publish.yml@8f87619b7f0122c39e14a32514ab3e4e0d4c3966 # v2.3.0
    secrets: inherit
